public enum AchievementName
{
	PICKING_UP_THE_PIECES = 0,
	HELLO_BENDY = 1,
	CROONER_TUNER = 2,
	THE_CREATOR = 3,
	MY_FAVORITE_SONG = 4,
	STRIKE_UP_THE_BAND = 5,
	COAST_TO_COAST = 6,
	CANADIAN_BACON = 7,
	THE_BELIEVER = 8,
	MAN_BEHIND_THE_CURTAIN = 9,
	JOHNNYS_BROKEN_HEART = 10,
}
